### ISSUE TITLE
Will there be a transform function like UMAP has?

### ISSUE THREAD

**Issue by yusuftalhatamer** [awslabs/amazon-denseclus#10]
For the full embedding/clustering job, it might be really good to have transform function so new data can be transformed and clustered without repeating the embedding. Similar to UMAPs transform function.

**Comment by momonga-ml** [comment]
@yusuftalhatamer Due to the nature of using 2 UMAP embeddings and then performing set operations on them, there is no way right now to run a transform or predict function. Issue #4 is currently setup for tracking a workaround to that limitation.
