### ISSUE TITLE
What preprocessing required for mix type of dataset ( continuous and categorical ) ?

### ISSUE THREAD

**Issue by monk1337** [awslabs/amazon-denseclus#13]
Hello Denseclus developers: I have one question regarding the the preprocessing,

If my dataset is the combination of continuous ( numerical ) and categorical values, What are the steps to use this repo? Do I need to preprocess my data before feeding to DenseClus function?

Thank you!

**Comment by sunbc0120** [comment]
Yes, preprocessing is needed. For ideas please refer to: https://scikit-learn.org/stable/modules/preprocessing.html
