### ISSUE TITLE
Is there a reason you didn't use DensMAP (e.g. `dens_lambda=1.0`) within DenseClus?

### ISSUE THREAD

**Issue by sgbaird** [awslabs/amazon-denseclus#15]
See https://umap-learn.readthedocs.io/en/latest/densmap_demo.html
@faris-k

**Comment by momonga-ml** [comment]
@sgbaird The main purpose is for clustering and not visualization. While DensMAP could potentially provide a different perspective on the data by preserving local densities, it might not necessarily contribute to achieving denser embeddings for the clustering objective.

**Comment by momonga-ml** [comment]
FYI, adding dictionary `kwargs` in #34 that 'should' be able to support this.
