### ISSUE TITLE
DenseClus and missing values

### ISSUE THREAD

**Issue by jbdatascience** [awslabs/amazon-denseclus#23]
Does DenseClus tolerate missing values in the dataset?
As for as I can see from the source code, I expect that missing values in the data have to be imputed before they are fed into DensClus, but I would like that to be confirmed.

**Comment by sunbc0120** [comment]
Hi, DenseClus won't tolerate missing values, as it aims at solving the clustering problem only. So use it as a single step of a pipeline, out of which the missing value shall be handled by another prior step.

Imputing is one way to handle missing values, among others like dropping, back-filling, forward-filling, median/mean/mode, special value marking, etc. It really depends on case-by-case. We won't make assumption that one way is better than another.
