### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by cwk20** [awslabs/amazon-denseclus#24]
from denseclus import DenseClus 

TypeError                                 Traceback (most recent call last)
C:\Temp\ipykernel_11700\3655304814.py in <cell line: 1>()
----> 1 from denseclus import DenseClus

~\anaconda3\lib\site-packages\denseclus\__init__.py in <module>
----> 1 from .DenseClus import DenseClus
      2 from .utils import extract_categorical, extract_numerical
      3 
      4 __version__ = "0.0.19"

~\anaconda3\lib\site-packages\denseclus\DenseClus.py in <module>
      3 import warnings
      4 
----> 5 import hdbscan
      6 import numpy as np
      7 import pandas as pd

~\anaconda3\lib\site-packages\hdbscan\__init__.py in <module>
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
      3 from .validity import validity_index
      4 from .prediction import (approximate_predict,
      5                          membership_vector,

~\anaconda3\lib\site-packages\hdbscan\hdbscan_.py in <module>
    507     leaf_size=40,
    508     algorithm="best",
--> 509     memory=Memory(cachedir=None, verbose=0),
    510     approx_min_span_tree=True,
    511     gen_min_span_tree=False,

TypeError: __init__() got an unexpected keyword argument 'cachedir'

What has gone wrong here? How can I fix this? I am using anaconda3.

**Comment by sunbc0120** [comment]
This is an issue caused by `joblib`.

Try to upgrade `hdbscan`: https://pypi.org/project/hdbscan/.

For more information see discussion here: https://github.com/scikit-learn-contrib/hdbscan/issues/565

**Comment by cwk20** [comment]
I have managed to get it  to work somehow.

I wasn't aware that it was caused by joblib.

Thank you for your comments!!
