### ISSUE TITLE
Denseclus on large data set

### ISSUE THREAD

**Issue by jovanaarsic** [awslabs/amazon-denseclus#27]
Hi, hi. 😊
I would  kindly ask for a little bit of help.
I have ta large data set (over 6mil rows and 20 columns ) with mixtured datatypes.

The idea was to implement the DenseClus.
(mix of umap embeddings for different data types with HDBSCAN).
I've implemented on subset oh 100K.
But the OOM error popped up really soon.

My core questions would be?
1. Is there option of fitting DanseClaus
3.  on this kind of dataset?
4. Recommendations related to prams? 
5. There is no possibility of transform the unseen data/ how to apply on entire data set?  
6. As I work on DataBricks, some recommendations regarding the memory-performance of indtance?
7. The strategy of dealing with this kind of task? 

 
Additional advices are welcoming. 🤗

**Comment by momonga-ml** [comment]
@jovanaarsic In your case, I would recommend not using it if the dataset size is so large that it cannot fit on single machine. Instead looking it to other algorithms for clustering support by Spark MLLib. Alternatively, you could sub-sample to get a dataset that fits on single machine and run.
