### ISSUE TITLE
Using denseclus with numeric only data

### ISSUE THREAD

**Issue by jbdatascience** [awslabs/amazon-denseclus#28]
How can I use denseclus with numeric only data?

Also: in utils.py I see that all categorical data is one hot encoded using pd.get_dummies(), which is appropriate for nominal categorical data. Not so for ordinal categorical data. 
My question: how to use DenseClus on ordinal categorical data?

**Comment by smart-patrol** [comment]
@jbdatascience @sunbc0120  This would just be an ordinal encoding of those values. Basically, a selection of "ordinal" or "categorical" then transform accordingly.
