### ISSUE TITLE
Dependence of clustering results on random seed

### ISSUE THREAD

**Issue by jbdatascience** [awslabs/amazon-denseclus#29]
When testing the DenseClus algorithm on a mixed type dataset, I discovered the strong dependence of clustering results on random seed used. 

My question: given this fact, what can I do to get reliable cluster results? My initial approach would be to target stable clustering results, but how to that?

**Comment by smart-patrol** [comment]
@jbdatascience  Random seed will be factor here because of the UMAP. It's neural network at heart, see: https://umap-learn.readthedocs.io/en/latest/reproducibility.html
