### ISSUE TITLE
Package doesn't work on Sagemaker

### ISSUE THREAD

**Issue by saujosai** [awslabs/amazon-denseclus#31]
It would be nice if this Amazon package would work on Amazon Sagemaker.
I can install regular hdbscan using conda from conda-forge, but both pip and conda fail to install Amazon-DenseClus. This using Datascience 2.0 Kernel in Sagemaker Studio.

**Comment by smart-patrol** [comment]
@saujosai  Can you post the failure here? 
If it's dockerized, like the SM training,inference,etc then it would work as custom image if passing requirements fails.
As you're using SageMaker Studio which is inside of containerized environment to begin with, this makes things different.

**Comment by momonga-ml** [comment]
See: https://github.com/awslabs/amazon-denseclus/blob/main/notebooks/04_JumpstartDenseClus.ipynb
