### ISSUE TITLE
Prediction on new points

### ISSUE THREAD

**Issue by Nick3523** [awslabs/amazon-denseclus#33]
Hello,

Firstly, many thanks for the great DenseClus project.
I was wondering if it is possible to make cluster prediction on a new point, like the approximate_predict(clusterer, points_to_predict) in [hdbscan](https://hdbscan.readthedocs.io/en/latest/api.html#hdbscan.prediction.approximate_predict).

I know DenseClus() has the boolean parameter 'prediction_data', but I didn't find how to make the predictions on new points.

Many thanks for your help.

**Comment by momonga-ml** [comment]
@Nick3523  Yes, agree. This has been a limiter. You'd have to get the UMAP points as well.

This is the same as: https://github.com/awslabs/amazon-denseclus/issues/4
